### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by trevor1097** [andrewyunt/TownyGUI#2]
Every time i type /tgui in console i get

> trevor1097 issued server command: /tgui
> [02:22:49] [Server thread/ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'tgui' in plugin TownyGUI v0.16
>     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
>     at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
>     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
> Caused by: java.lang.Error: Unresolved compilation problem: 
>     The method colorizeStringList(List<String>) is undefined for the type Utils
>     at com.andrewyunt.townygui.Menu.openMenu(Menu.java:82) ~[?:?]
>     at com.andrewyunt.townygui.Menu.<init>(Menu.java:40) ~[?:?]
>     at com.andrewyunt.townygui.TownyGUI.onCommand(TownyGUI.java:67) ~[?:?]
>     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     ... 15 more

**Comment by andrewyunt** [comment]
The tgui command is for players only, and cannot be used from the console.

**Comment by trevor1097** [comment]
i am running it in game. this is the message i get in console. didn't make that clear the first time
